#!/usr/bin/env python3
# CGI script: test.py
# Test CGI execution via webserv

import os
import sys
from datetime import datetime

def print_header():
    print("Content-Type: text/html; charset=utf-8")
    print()

def print_html():
    print("<!DOCTYPE html>")
    print('<html lang="en"><head><meta charset="UTF-8">')
    print("<title>CGI Test - Python</title>")
    print("""<style>
        body { font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; background: #f5f5f5; }
        h1 { color: #333; border-bottom: 2px solid #6f42c1; padding-bottom: 10px; }
        .card { background: white; border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #f8f9fa; }
        code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }
        .success { background: #d4edda; border: 1px solid #c3e6cb; border-radius: 4px; padding: 15px; color: #155724; margin: 15px 0; }
        a { color: #007bff; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 0.9em; }
    </style>""")
    print("</head><body>")
    print("<h1>CGI Test - Python</h1>")
    print('<div class="card">')
    print('<div class="success"><strong>CGI is working!</strong> This page was generated by a Python CGI script.</div>')
    print("<h2>Environment Variables</h2>")
    print("<table><tr><th>Variable</th><th>Value</th></tr>")
    relevant_vars = [
        "REQUEST_METHOD", "SCRIPT_NAME", "PATH_INFO", "QUERY_STRING",
        "CONTENT_TYPE", "CONTENT_LENGTH", "SERVER_NAME", "SERVER_PORT",
        "SERVER_PROTOCOL", "HTTP_HOST", "HTTP_USER_AGENT", "HTTP_ACCEPT",
        "HTTP_ACCEPT_LANGUAGE", "HTTP_CONNECTION", "REMOTE_ADDR", "REMOTE_PORT"
    ]
    for var in relevant_vars:
        value = os.environ.get(var, "Not set")
        if len(value) > 100:
            value = value[:100] + "..."
        print(f"<tr><td><code>{var}</code></td><td>{value}</td></tr>")
    print("</table>")

    print("<h2>Request Body (if POST)</h2>")
    content_length = os.environ.get("CONTENT_LENGTH", "0")
    if content_length and int(content_length) > 0:
        body = sys.stdin.read(int(content_length))
        print(f"<div class='card'><pre><code>{body}</code></pre></div>")
    else:
        print("<p>No request body (GET request or empty body).</p>")

    print("<h2>Extra Info</h2>")
    print(f"<p><strong>Current time:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>")
    print(f"<p><strong>Python version:</strong> {sys.version}</p>")
    print(f"<p><strong>Working directory:</strong> {os.getcwd()}</p>")

    print('<p><a href="/">← Back to Home</a> | <a href="/cgi-bin/test.sh">CGI Bash Test</a></p>')
    print("</div>")
    print('<div class="footer"><p>Webserv Test Suite | CGI Python Test</p></div>')
    print("</body></html>")

if __name__ == "__main__":
    print_header()
    print_html()
