#!/bin/bash
# CGI script: test.sh - Bash CGI test
# Demonstrates CGI execution with shell scripts

echo "Content-Type: text/html; charset=utf-8"
echo ""

cat << 'HTMLHEADER'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGI Test - Bash</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; background: #f5f5f5; }
        h1 { color: #333; border-bottom: 2px solid #6f42c1; padding-bottom: 10px; }
        .card { background: white; border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin: 20px 0; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #f8f9fa; }
        code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }
        .success { background: #d4edda; border: 1px solid #c3e6cb; border-radius: 4px; padding: 15px; color: #155724; margin: 15px 0; font-weight: bold; }
        a { color: #007bff; text-decoration: none; }
        a:hover { text-decoration: underline; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 0.9em; }
        pre { background: #f8f9fa; padding: 15px; border: 1px solid #ddd; border-radius: 4px; overflow-x: auto; }
    </style>
</head>
<body>
HTMLHEADER

echo "<h1>CGI Test - Bash</h1>"
echo '<div class="card">'
echo '<div class="success">CGI is working! This page was generated by a Bash CGI script.</div>'
echo "<h2>CGI Environment Variables</h2>"
echo "<table><tr><th>Variable</th><th>Value</th></tr>"

# Print relevant environment variables
for var in REQUEST_METHOD SCRIPT_NAME PATH_INFO QUERY_STRING CONTENT_TYPE CONTENT_LENGTH SERVER_NAME SERVER_PORT SERVER_PROTOCOL HTTP_HOST HTTP_USER_AGENT HTTP_ACCEPT REMOTE_ADDR REMOTE_PORT; do
    value="${!var:-Not set}"
    # Truncate long values
    if [ ${#value} -gt 100 ]; then
        value="${value:0:100}..."
    fi
    printf "<tr><td><code>%s</code></td><td>%s</td></tr>\n" "$var" "$value"
done

echo "</table>"

echo "<h2>Request Information</h2>"
echo "<p><strong>Current time:</strong> $(date '+%Y-%m-%d %H:%M:%S %Z')</p>"
echo "<p><strong>Shell:</strong> $BASH_VERSION</p>"
echo "<p><strong>Working directory:</strong> $(pwd)</p>"

# Show request body if POST
content_length="${CONTENT_LENGTH:-0}"
if [ "$content_length" -gt 0 ] 2>/dev/null; then
    echo "<h2>Request Body</h2>"
    echo "<pre><code>"
    head -c "$content_length"
    echo ""
    echo "</code></pre>"
fi

echo '<p><a href="/">← Back to Home</a> | <a href="/cgi-bin/test.py">CGI Python Test</a></p>'
echo '</div>'
echo '<div class="footer"><p>Webserv Test Suite | CGI Bash Test</p></div>'
echo "</body></html>"
