server {
    listen 8080;
    server_name localhost;

    root ./site/www;
    index index.html;
    client_max_body_size 131072;

    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 405 /errors/405.html;
    error_page 413 /errors/413.html;
    error_page 431 /errors/431.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;
    error_page 505 /errors/505.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /assets {
        root ./site/www/assets;
        allow_methods GET;
        autoindex off;
    }

    location /about {
        root ./site/www/about;
        allow_methods GET;
        index index.html;
        autoindex off;
    }

    location /docs {
        root ./site/www/docs;
        allow_methods GET;
        index index.html;
        autoindex off;
    }

    location /files {
        root ./site/www/files;
        allow_methods GET;
        autoindex on;
    }

    location /upload {
        root ./site/www/upload;
        allow_methods GET POST;
        upload_store ./site/www/uploads;
        index index.html;
        autoindex off;
    }

    location /uploads {
        root ./site/www/uploads;
        allow_methods GET DELETE;
        autoindex on;
    }

    location /cgi-bin {
        root ./site/www/cgi-bin;
        allow_methods GET POST;
        cgi_extension .py .js;
        cgi_path /usr/bin/python3  /usr/local/bin/node;
    }

    location /get-only {
        root ./site/www;
        allow_methods GET;
        autoindex off;
    }

    location /legacy {
        return 301 /redirected.html;
    }
}

server {
    listen 8081;
    server_name localhost;

    root ./site/www_alt;
    index index.html;
    client_max_body_size 131072;

    error_page 404 /404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }
}
