server {
	listen 8080;
	server_name localhost;
	root ./site/www123;
	root ./site/www23;
	root ./site/www3;
	root ./site/www;
	client_max_body_size 1000000000; #10; #1000000000;
	index test_index1.html index_test_1.htm; 
	error_page 404 403 406 405 413 /error_pages/404.html;
	error_page 400 /error_pages/400.html;
	error_page 500 error_pages/500.html;
	error_page 505 error_pages/505.html;

	location / {
		allow_methods GET;
		autoindex off;
	}

	location /upload {
		root ./site/www/upload;
		allow_methods GET POST DELETE;
		upload_store ./site/www/uploads;
		index index.html;
		autoindex on;
	}

	# location /delete_page {
	#	 root ./site/www/uploads;
	#	 allow_methods GET DELETE;
	# 	index del_index.html;
	#	 autoindex off;
	# }

	location /image {
		root ./site/www/image;
		allow_methods GET;
		autoindex on;
	}

	location /image/jpef {
		root ./site/www/image/jpef;
		allow_methods GET;
		autoindex on;
	}

	location /cgi-bin {
		root ./site/www/cgi-bin;
		allow_methods GET POST;
		cgi_extension .py; 
		cgi_path /usr/bin/python3;
	}

	# Ask ChatGPT if for different cgi_extentions we need different location path or can be the same 
	# with multiple "cgi_extention" 
	# location /cgi-bin {
	#	 root ./www/cgi-bin;
	#	 allow_methods GET POST;
	#	 cgi_extension .php; // main.py
	#	 cgi_path /usr/bin/python3;
	# }

	location /old-new-page {
		root ./site/www/large;
		allow_methods GET DELETE;
		autoindex off;
	}

	location /old-page {
		return 301 /old-new-page;
	}
}

server {
	listen 8080;
	server_name test.localhost;


	root ./site/www/small;
	# index index.html;

	client_max_body_size 500000;

	error_page 404 ./www_test/errors/404.html;

	location /new-old-page {
		root ./site/www/medium;
	}

	location /old-page {
		return 301 /new-old-page;
	}

	location / {
		allow_methods GET;
		autoindex off;
	}

	location /api {
		allow_methods GET POST;
		autoindex off;
	}
}

server {
	listen 8080;
	server_name test.test2.localhost;
	root ./site/www/medium;

	location / {
		allow_methods GET;
		autoindex off;
	}
}