server {
    # The rest can have many values. 
    listen 8080; # listen = port => can be only one
    server_name localhost1;
    root ./www1;    # root can be onlt one
    client_max_body_size 1000000000;
    index test_index1.html index_test_1.htm; 
    # Some more comments
    error_page 404 403 406 405 413 ./www/errors/404.html;
    error_page 500 ./www/errors/500.html;

    location / {
        allow_methods GET;
        autoindex off; # and more comments more more more more more
    }

    location /upload { # and another one...
        allow_methods GET POST DELETE;
        upload_store ./www/uploads;
        autoindex on;
    }

    location /images {
        root ./www/images;
        allow_methods GET;
        autoindex on;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        allow_methods GET POST;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }

    location /old-page {
        return 301 /;
    }
}

server {
    listen 8081;
    server_name test.localhost;

    root ./www_test;
    index index.html;

    client_max_body_size 500000;

    error_page 404 ./www_test/errors/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /api {
        allow_methods GET POST;
        autoindex off;
    }
}
