server {
    listen 8080;
    server_name small.localhost;

    root ./site/www;
    client_max_body_size 10;

    error_page 400 /error_pages/400.html;
    error_page 413 /error_pages/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /upload {
        root ./site/www/upload;
        allow_methods GET POST DELETE;
        upload_store ./site/www/uploads;
        autoindex on;
    }
}

server {
    listen 8080;
    server_name medium.localhost;

    root ./site/www;
    client_max_body_size 100;

    error_page 400 /error_pages/400.html;
    error_page 413 /error_pages/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /upload {
        root ./site/www/upload;
        allow_methods GET POST DELETE;
        upload_store ./site/www/uploads;
        autoindex on;
    }
}

server {
    listen 8080;
    server_name large.localhost;

    root ./site/www;
    client_max_body_size 1000;

    error_page 400 /error_pages/400.html;
    error_page 413 /error_pages/404.html;

    location / {
        allow_methods GET;
        autoindex off;
    }

    location /upload {
        root ./site/www/upload;
        allow_methods GET POST DELETE;
        upload_store ./site/www/uploads;
        autoindex on;
    }
}