server {
     listen 127.0.0.1:8080;
    server_name small.localhost;

    root ./site/www/small;
    index index.html;

    client_max_body_size 10;

    location / {
        allow_methods GET;
    }
}

server {
     listen 127.0.0.1:8080;
    server_name medium.localhost;

    root ./site/www/medium;
    index index.html;

    client_max_body_size 100;

    location / {
        allow_methods GET;
    }
}

server {
     listen 127.0.0.1:8080;
    server_name large.localhost;

    root ./site/www/large;
    index index.html;

    client_max_body_size 1000;

    location / {
        allow_methods GET;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name another.localhost;

    root ./site/www/small;
    index index.html;

    location / {
        allow_methods GET;
    }
}