server {
    listen 8080; # sdg af g df g df g df g ds avr ef d
    server_name localhost1; 
    #sdfkguaf adufh kdjfb kusdkvjb nkdjb kjdb 
    root ./www1;
    index test_index1.html index_test_1.htm;
    client_max_body_size 1000000;

}
